// ─── 組み込みポリシーテンプレート ───────────────────────────────────────────────
//
// ユーザーが "テンプレートから作る" モードで選択できる初期テンプレート群。
// 各テンプレートは AlertPolicy / SummaryPolicy の partial を持ち、
// ポリシー作成ダイアログでそのまま初期値として使われる。

import type {
  PolicyTemplate,
  AlertPolicy,
  SummaryPolicy,
} from './types';

// ── Alert Policy テンプレート ─────────────────────────────────────────────────

const ALERT_TEMPLATES: PolicyTemplate[] = [
  {
    id:              'tmpl_churn_risk',
    name:            'チャーンリスク',
    description:     'コミュニケーション途絶・アクティブプロジェクトなし・ヘルス低下の複合条件',
    category:        'alert',
    object_type:     'company',
    signal_category: 'risk',
    icon:            '⚠️',
    policy: {
      object_type:     'company',
      signal_category: 'risk',
      scope:           'per_entity',
      condition_logic: 'AND',
      interpretation_mode: 'structured_only',
      structured_conditions: [
        { id: 'c1', field: 'comm_blank_days', operator: 'gte', value: 45, label: '45日以上コミュニケーションなし' },
        { id: 'c2', field: 'active_project_count', operator: 'eq', value: 0, label: 'アクティブプロジェクトなし' },
      ],
      output: {
        severity:           'high',
        title:              'チャーンリスク: {{company_name}}',
        description:        'コミュニケーション {{blank_days}} 日空白、アクティブプロジェクトなし。',
        recommended_action: 'カスタマーサクセスによる関係強化アクションを検討してください。',
        category_tag:       'churn_risk',
      },
    } as Partial<AlertPolicy>,
  },
  {
    id:              'tmpl_comm_blank',
    name:            'コミュニケーション空白',
    description:     '一定期間コミュニケーションがない企業を検出',
    category:        'alert',
    object_type:     'company',
    signal_category: 'risk',
    icon:            '📭',
    policy: {
      object_type:     'company',
      signal_category: 'risk',
      scope:           'per_entity',
      condition_logic: 'AND',
      interpretation_mode: 'structured_only',
      structured_conditions: [
        { id: 'c1', field: 'comm_blank_days', operator: 'gte', value: 30, label: '30日以上コミュニケーションなし' },
      ],
      output: {
        severity:    'medium',
        title:       '通信空白: {{company_name}} ({{blank_days}}日)',
        description: '最終コミュニケーションから {{blank_days}} 日が経過しています。',
        recommended_action: 'メールまたはチャットで近況確認を行ってください。',
        category_tag: 'communication',
      },
    } as Partial<AlertPolicy>,
  },
  {
    id:              'tmpl_expansion_signal',
    name:            '拡張シグナル',
    description:     'アクティブプロジェクト増加・エンゲージメント向上など拡張の機会を検出',
    category:        'alert',
    object_type:     'company',
    signal_category: 'opportunity',
    icon:            '📈',
    policy: {
      object_type:     'company',
      signal_category: 'opportunity',
      scope:           'per_entity',
      condition_logic: 'AND',
      interpretation_mode: 'ai_assisted',
      structured_conditions: [
        { id: 'c1', field: 'active_project_count', operator: 'gte', value: 2, label: 'アクティブプロジェクト2件以上' },
      ],
      ai_hint: '拡張提案に繋がるポジティブシグナルを重視してください',
      output: {
        severity:    'info',
        title:       '拡張機会: {{company_name}}',
        description: '{{active_project_count}} 件のアクティブプロジェクトが稼働中です。',
        recommended_action: 'アップセル・クロスセルの提案タイミングを検討してください。',
        category_tag: 'expansion',
      },
    } as Partial<AlertPolicy>,
  },
  {
    id:              'tmpl_critical_support',
    name:            'Critical サポートケース',
    description:     'Critical 重要度のサポートケースが未解決の企業をアラート',
    category:        'alert',
    object_type:     'company',
    signal_category: 'risk',
    icon:            '🚨',
    policy: {
      object_type:     'company',
      signal_category: 'risk',
      scope:           'per_entity',
      condition_logic: 'AND',
      interpretation_mode: 'structured_only',
      structured_conditions: [
        { id: 'c1', field: 'open_critical_support_count', operator: 'gte', value: 1, label: 'Critical サポートが1件以上' },
      ],
      output: {
        severity:    'critical',
        title:       '未解決 Critical: {{company_name}} ({{count}}件)',
        description: '{{count}} 件の Critical サポートケースが未解決です。',
        recommended_action: 'サポートチームとエスカレーション状況を確認してください。',
        category_tag: 'support_critical',
      },
    } as Partial<AlertPolicy>,
  },
  {
    id:              'tmpl_support_surge',
    name:            'サポートキュー急増',
    description:     '直近にサポートケースが急増したキューを集計ベースで検出',
    category:        'alert',
    object_type:     'support_queue',
    signal_category: 'risk',
    icon:            '🔥',
    policy: {
      object_type:     'support_queue',
      signal_category: 'risk',
      scope:           'aggregate',
      condition_logic: 'AND',
      interpretation_mode: 'structured_only',
      structured_conditions: [
        { id: 'c1', field: 'new_cases_last_24h', operator: 'gte', value: 10, label: '24時間以内に10件以上新規' },
        { id: 'c2', field: 'open_count', operator: 'gte', value: 30, label: 'オープン件数30件以上' },
      ],
      output: {
        severity:    'high',
        title:       'サポートキュー急増 ({{new_count}}件/24h)',
        description: '直近24時間で {{new_count}} 件の新規ケースが発生し、合計 {{open_count}} 件がオープンです。',
        recommended_action: 'CSE リソースの追加配置を検討してください。',
        category_tag: 'queue_surge',
      },
    } as Partial<AlertPolicy>,
  },
  {
    id:              'tmpl_no_decision_maker',
    name:            '意思決定者未登録',
    description:     '意思決定者（Decision Maker）が登録されていない企業をリスクとして検出',
    category:        'alert',
    object_type:     'company',
    signal_category: 'risk',
    icon:            '👤',
    policy: {
      object_type:     'company',
      signal_category: 'risk',
      scope:           'per_entity',
      condition_logic: 'AND',
      interpretation_mode: 'structured_only',
      structured_conditions: [
        { id: 'c1', field: 'decision_maker_count', operator: 'eq', value: 0, label: '意思決定者 0名' },
      ],
      output: {
        severity:    'medium',
        title:       '意思決定者未登録: {{company_name}}',
        description: '組織内に意思決定者 (high influence) が登録されていません。',
        recommended_action: '担当者リストを見直し、キーパーソンを特定・登録してください。',
        category_tag: 'people_risk',
      },
    } as Partial<AlertPolicy>,
  },
];

// ── Summary Policy テンプレート ───────────────────────────────────────────────

const SUMMARY_TEMPLATES: PolicyTemplate[] = [
  {
    id:       'tmpl_company_summary_default',
    name:     'Company Summary（標準）',
    description: 'Evidence・Alert・People を網羅的に分析し、変化・機会・リスク・次の一手を攻略順に生成',
    category: 'summary',
    icon:     '📋',
    policy: {
      target:             'company_summary',
      generation_trigger: 'on_staleness',
      input_scope:        'all_evidence',
      summary_focus:      '直近の変化・フェーズを把握し、拡大・活性化の機会を重点的に分析する。リスクは機会の後に補足として整理し、次の一手を具体的に提示する',
      output_schema: [
        { key: 'summary',               type: 'text',     required: true,  max_length: 400, instruction: '企業全体の状況を400字以内で要約。直近の変化→機会→リスク→次の一手の順で述べる' },
        { key: 'overall_health',        type: 'severity', required: true },
        { key: 'key_opportunities',     type: 'list',     required: false, instruction: '攻略・拡大・活性化の機会を2件まで列挙' },
        { key: 'key_risks',             type: 'list',     required: true,  instruction: '要注意リスクを3件まで列挙。リスクがなければ空配列' },
        { key: 'recommended_next_action', type: 'text',   required: true,  max_length: 200 },
      ],
      freshness_rule: { stale_after_days: 7, auto_regenerate_on_stale: false, force_on_critical_alert: true },
      approval_rule:  'require_review',
    } as Partial<SummaryPolicy>,
  },
  {
    id:       'tmpl_company_summary_weekly',
    name:     'Company Summary（週次自動）',
    description: '毎週月曜に全企業の Summary を自動再生成し、approved でなければ上書き',
    category: 'summary',
    icon:     '🔄',
    policy: {
      target:             'company_summary',
      generation_trigger: 'scheduled',
      schedule_cron:      '0 9 * * 1',  // 毎週月曜 9:00
      input_scope:        'recent_only',
      input_recent_days:  30,
      summary_focus:      '直近30日の変化・トレンドを中心に分析する',
      output_schema: [
        { key: 'summary',               type: 'text',     required: true,  max_length: 300 },
        { key: 'overall_health',        type: 'severity', required: true },
        { key: 'key_risks',             type: 'list',     required: true },
        { key: 'recommended_next_action', type: 'text',   required: true },
      ],
      freshness_rule: { stale_after_days: 7, auto_regenerate_on_stale: true },
      approval_rule:  'auto_approve',
    } as Partial<SummaryPolicy>,
  },
  {
    id:       'tmpl_company_summary_expansion',
    name:     'Company Summary（攻略・拡大型）',
    description: '機会・upsell・活用促進を主役に分析。リスク言及は最大1件に抑制',
    category: 'summary',
    icon:     '🚀',
    policy: {
      target:             'company_summary',
      generation_trigger: 'manual',
      input_scope:        'all_evidence',
      summary_focus: [
        '【攻略・拡大型モード】',
        'このサマリーは「次の提案・関係深化」のための情報として構成すること。',
        '',
        '## summary 本文の構成（必須）',
        '1. 直近の変化・フェーズ現在地（1文）',
        '2. 拡大・upsell・活用促進の機会（2〜3文・主役として重く書く）',
        '3. リスクがある場合のみ1文で触れる（なければ省略）',
        '4. 次の提案・関係深化アクション（1文）',
        '',
        '## key_opportunities（必須・2〜3件）',
        '機会を具体的かつ前向きに列挙すること。根拠はProject・Support・Evidenceから。',
        '',
        '## key_risks（最大1件・なければ空配列）',
        '実際に懸念がある場合のみ記載。無理にリスクを作らない。',
        '',
        '## recommended_next_action',
        '必ず「提案 / 活性化 / upsell / 関係深化」を起点とした1文（60〜80字）にすること。',
        '例: 「〇〇さんに△△のユースケース提案を持ちかけ、次フェーズへの移行を促す」',
        '火消し・状況確認・解約防止は起点にしない（リスク監視型の役割）。',
      ].join('\n'),
      output_schema: [
        { key: 'summary',                 type: 'text',     required: true,  max_length: 350, instruction: '直近変化(1文)→機会・拡大余地(2〜3文, 主役)→リスク(あれば1文)→次の提案(1文)の順。機会を重点的に記述。' },
        { key: 'overall_health',          type: 'severity', required: true },
        { key: 'key_opportunities',       type: 'list',     required: true,  instruction: '攻略・upsell・活用促進の機会を2〜3件。なければ1件でも可。空配列は不可。' },
        { key: 'key_risks',               type: 'list',     required: false, instruction: '実際に懸念がある場合のみ最大1件。懸念がなければ必ず空配列。' },
        { key: 'recommended_next_action', type: 'text',     required: true,  max_length: 150, instruction: '「提案・活性化・upsell・関係深化」を起点とした1文アクション（60〜80字）。火消し・状況確認は書かない。' },
      ],
      freshness_rule: { stale_after_days: 7, auto_regenerate_on_stale: false, force_on_critical_alert: false },
      approval_rule:  'require_review',
    } as Partial<SummaryPolicy>,
  },
  {
    id:       'tmpl_company_summary_risk_watch',
    name:     'Company Summary（リスク監視型）',
    description: 'チャーンリスク・サポート逼迫を主役に分析。機会言及は最大1件に抑制',
    category: 'summary',
    icon:     '🔍',
    policy: {
      target:             'company_summary',
      generation_trigger: 'manual',
      input_scope:        'all_evidence',
      summary_focus: [
        '【リスク監視型モード】',
        'このサマリーは「解約・チャーン防止・リスク解消」のための情報として構成すること。',
        '',
        '## summary 本文の構成（必須）',
        '1. 直近のリスク状況・現在地（1文）',
        '2. 主要リスク（2〜3文・主役として重く書く。根拠と深刻度を明示）',
        '3. 機会がある場合のみ1文で触れる（なければ省略）',
        '4. 緊急アクション・火消し方針（1文）',
        '',
        '## key_risks（必須・2〜3件）',
        'リスクを深刻度順に具体的に列挙。根拠・影響・放置した場合のリスクを明示すること。',
        '',
        '## key_opportunities（最大1件・なければ空配列）',
        '機会がある場合のみ記載。無理に機会を作らない。',
        '',
        '## recommended_next_action',
        '必ず「状況確認 / 火消し / 要因切り分け / 解約防止」を起点とした1文（60〜80字）にすること。',
        '例: 「〇〇さんに現状ヒアリングを設定し、サポート逼迫の根本原因を特定する」',
        '提案・upsell・関係深化は起点にしない（攻略型の役割）。',
      ].join('\n'),
      output_schema: [
        { key: 'summary',                 type: 'text',     required: true,  max_length: 350, instruction: 'リスク状況(1文)→主要リスク(2〜3文, 主役)→機会(あれば1文)→緊急アクション(1文)の順。リスクを重点的に記述。' },
        { key: 'overall_health',          type: 'severity', required: true },
        { key: 'key_risks',               type: 'list',     required: true,  instruction: 'リスクを深刻度順に2〜3件。根拠・影響・放置時のリスクを明示。1件だけの場合は根拠を詳しく書く。' },
        { key: 'key_opportunities',       type: 'list',     required: false, instruction: '機会がある場合のみ最大1件。機会がなければ必ず空配列。' },
        { key: 'recommended_next_action', type: 'text',     required: true,  max_length: 150, instruction: '「状況確認・火消し・要因切り分け・解約防止」を起点とした1文アクション（60〜80字）。提案・upsellは書かない。' },
      ],
      freshness_rule: { stale_after_days: 7, auto_regenerate_on_stale: false, force_on_critical_alert: true },
      approval_rule:  'require_review',
    } as Partial<SummaryPolicy>,
  },
  {
    id:       'tmpl_company_summary_report',
    name:     'Company Summary（マネージャー報告型）',
    description: '上長報告・社内共有向け。現状・注目点・懸念・次アクションの報告メモ形式',
    category: 'summary',
    icon:     '📊',
    policy: {
      target:             'company_summary',
      generation_trigger: 'manual',
      input_scope:        'all_evidence',
      summary_focus: [
        '【マネージャー報告型モード】',
        'このサマリーは上長への報告・社内共有メモとして使える形式に構成すること。',
        '長文ではなく「報告メモ」として読めるよう、構造を明確にすること。',
        '',
        '## summary 本文の構成（必須・この4項目を必ず1文ずつ含める）',
        '【現状】現在のフェーズ・状況を1文で。',
        '【注目点】直近で重要な変化・動きを1文で。',
        '【懸念】リスクや要注意事項を1文で（なければ「特記事項なし」）。',
        '【次アクション】優先アクションを1文で。',
        '',
        '合計4文・200字以内を厳守すること。上記4項目のラベルは本文に書かない。',
        '',
        '## key_opportunities / key_risks（各最大1件）',
        '最も重要なものだけ1件ずつ。どちらも不要なら空配列。',
        '',
        '## recommended_next_action',
        '必ず「共有 / 判断依頼 / 次会議論点 / 承認依頼」を起点とした1文（50〜70字）にすること。',
        '例: 「週次MTGで解約リスクを共有し、対応方針の判断を仰ぐ」',
        '長文のアクション指示は書かない。',
      ].join('\n'),
      output_schema: [
        { key: 'summary',                 type: 'text',     required: true,  max_length: 200, instruction: '【現状】【注目点】【懸念】【次アクション】を各1文で。合計200字以内。箇条書き不可・連続した文章形式。' },
        { key: 'overall_health',          type: 'severity', required: true },
        { key: 'key_opportunities',       type: 'list',     required: false, instruction: '最重要の機会を1件のみ。なければ空配列。' },
        { key: 'key_risks',               type: 'list',     required: false, instruction: '最重要のリスクを1件のみ。なければ空配列。' },
        { key: 'recommended_next_action', type: 'text',     required: true,  max_length: 100, instruction: '「共有・判断依頼・次会議論点」を起点とした1文（50〜70字）。長いアクション指示は書かない。' },
      ],
      freshness_rule: { stale_after_days: 14, auto_regenerate_on_stale: false },
      approval_rule:  'require_review',
    } as Partial<SummaryPolicy>,
  },
  {
    id:       'tmpl_support_summary_default',
    name:     'Support Summary（標準）',
    description: 'サポートケースの背景・緊急度・推奨対応を分析',
    category: 'summary',
    icon:     '🎧',
    policy: {
      target:             'support_summary',
      generation_trigger: 'manual',
      input_scope:        'all_evidence',
      summary_focus:      '問題の根本原因・対応優先度・顧客への影響を重点的に分析する',
      output_schema: [
        { key: 'issue_summary',     type: 'text',     required: true,  max_length: 300 },
        { key: 'urgency',           type: 'severity', required: true },
        { key: 'root_cause',        type: 'text',     required: false },
        { key: 'recommended_reply', type: 'text',     required: true,  max_length: 400 },
      ],
      freshness_rule: { stale_after_days: 1, auto_regenerate_on_stale: false },
      approval_rule:  'auto_approve',
    } as Partial<SummaryPolicy>,
  },
];

// ── エクスポート ───────────────────────────────────────────────────────────────

export const POLICY_TEMPLATES: PolicyTemplate[] = [
  ...ALERT_TEMPLATES,
  ...SUMMARY_TEMPLATES,
];

export const ALERT_POLICY_TEMPLATES  = ALERT_TEMPLATES;
export const SUMMARY_POLICY_TEMPLATES = SUMMARY_TEMPLATES;

/** 利用可能なフィールド一覧（条件ビルダーのドロップダウン用） */
export const ALERT_CONDITION_FIELDS: Record<
  string,
  { label: string; type: 'number' | 'string' | 'boolean'; objectTypes: string[] }
> = {
  comm_blank_days:              { label: 'コミュニケーション空白日数',        type: 'number',  objectTypes: ['company'] },
  active_project_count:         { label: 'アクティブプロジェクト数',          type: 'number',  objectTypes: ['company'] },
  open_critical_support_count:  { label: 'Critical サポートオープン数',       type: 'number',  objectTypes: ['company'] },
  open_support_count:           { label: 'サポートオープン総数',               type: 'number',  objectTypes: ['company'] },
  decision_maker_count:         { label: '意思決定者数',                       type: 'number',  objectTypes: ['company'] },
  overall_health:               { label: '健全性（overall_health）',          type: 'string',  objectTypes: ['company'] },
  phase_stagnation_days:        { label: 'フェーズ停滞日数',                   type: 'number',  objectTypes: ['company'] },
  open_alert_count:             { label: 'オープンアラート数',                  type: 'number',  objectTypes: ['company'] },
  open_action_count:            { label: 'オープンアクション数',                type: 'number',  objectTypes: ['company'] },
  case_severity:                { label: 'ケース重要度',                        type: 'string',  objectTypes: ['support_case'] },
  case_status:                  { label: 'ケースステータス',                    type: 'string',  objectTypes: ['support_case'] },
  case_waiting_hours:           { label: 'ケース待機時間（時間）',              type: 'number',  objectTypes: ['support_case'] },
  new_cases_last_24h:           { label: '新規ケース数（24h）',                type: 'number',  objectTypes: ['support_queue'] },
  open_count:                   { label: 'キューオープン件数',                  type: 'number',  objectTypes: ['support_queue'] },
};
